/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import medal from './medal.glb'
import { useFrame } from 'react-three-fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(medal)

  useFrame((state, delta) => {
    if (group.current) {
      group.current.rotation.y += 0.01
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.001']} position={[0.12, 0.05, 0.4]} scale={1} rotation={[0.75, -0.25, 0.2]}>
      </mesh>
    </group>
  )
}

useGLTF.preload(medal)
